FROM centos:7

RUN curl -L 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm' > /tmp/epel.rpm && \
    rpm -i /tmp/epel.rpm

RUN yum install -y rpm-build

# RPM build requires the user to actually exist.
ARG USER_UID=1000
ARG USER_GID=1000
RUN groupadd -o -g $USER_GID build && useradd -o -u $USER_UID -g $USER_GID -d /build --create-home build
WORKDIR /build

RUN chmod 755 /build

# Build & install the libjwt rpm
COPY rpm_specs/libjwt.spec /build/rpm_specs/libjwt.spec
RUN grep BuildRequires rpm_specs/libjwt.spec | sed -e 's|^BuildRequires: ||' | xargs yum install -y
USER build
RUN rpmbuild -ba rpm_specs/libjwt.spec
USER root
RUN rpm -i /build/rpmbuild/RPMS/x86_64/libjwt-[0-9]*.rpm

# Build the mod_proxy_jwt_auth rpm
COPY rpm_specs/mod_proxy_jwt_auth.spec /build/rpm_specs/mod_proxy_jwt_auth.spec
RUN grep BuildRequires rpm_specs/mod_proxy_jwt_auth.spec | sed -e 's|^BuildRequires: ||' | xargs yum install -y

COPY . /build/mod_proxy_jwt_auth
RUN chown -R $USER_UID:$USER_GID /build/mod_proxy_jwt_auth

USER build
# The cp is to make the path friendlier and to allow the image built libjwt to be copied out
RUN rpmbuild -ba rpm_specs/mod_proxy_jwt_auth.spec 
USER root
RUN mkdir -p /RPMS && cp -r /build/rpmbuild/RPMS/* /RPMS && chmod -R 755 /RPMS
CMD ["ls", "-al", "/RPMS"]
